# Tightening pass: replaces whole paragraphs by exact-match against current text.
from docx import Document

R = {
9: "StudyMate is an agent harness built from scratch in Python 3.12 during a three-week lab at the University of Passau. It serves one domain: a student drops lecture slides, PDFs, and exercise sheets into a read-only folder, and the agent turns that material into an Obsidian-style knowledge base of interlinked concept notes, lecture summaries, flashcards, and Mermaid mind maps. Afterwards it can lint the vault for broken links and quiz the student about the material.",

10: "This report has two halves. The first explains the control loop (Section II) and then the memory handling, short- and long-term (Section III). The second describes where the team exceeded the lab's minimum requirements (Section IV) and which extensions we considered and did not pursue (Section V). Code claims refer to the repository as delivered at the end of week 3: roughly 7,800 lines of Python under src/study_agent plus a pytest suite of comparable size.",

19: "A text response with no tool calls is the normal exit: the engine closes the run, records metrics and a trace, and returns. The exit statuses are success, max_iterations, empty, and error, so the Prometheus counters can separate \"the model gave up\", \"the model looped\", and \"infrastructure failed\". Two recovery paths exist. An empty response gets a synthetic user message (\"Your last response was empty. Continue the requested task now.\") and the loop continues instead of returning a blank answer. A context overflow the estimate missed forces one compaction and retries the iteration exactly once; a second overflow terminates the run.",

23: "The tool layer is a contract, not a collection of functions. BaseTool requires a name, a description, and a JSON schema for parameters, which to_openai_schema() renders for the model; execute() returns a string, and by convention failures come back as strings starting with \"Error\", not as exceptions. ToolRegistry.execute() enforces that: it looks the tool up, runs the permission gate, executes inside a try/except that converts any surviving exception into an error observation, and emits latency and status metrics. The model always receives an observation it can read and act on, the lab text's communicating failures upstream, and a raising tool cannot crash the loop mid-iteration.",

24: "The same method is where the week 3 permission system attaches. With a policy configured, each call is evaluated against an ordered rule list (first match wins; unmatched calls default to require-user-confirmation) and one of three outcomes applies. The detail that matters for safety: if a confirmation is required but no interactive handler exists (tests, non-interactive runs, or a handler that itself throws), the call is treated as denied. Fail-closed, as the brief describes for the full-access tier.",

26: "Instrumentation is bolted on, not woven in. The engine fires run_start, run_end, tool_start, and tool_end events to registered callbacks; the registry exposes an on_permission_decision seam; metrics, JSONL traces, and Langfuse export subscribe at assembly time in the CLI. Listener exceptions are caught at the seam, so a broken listener cannot break a run. This is the decoupled lifecycle-hook mechanism the week 3 brief asks for, and it pays off in practice: the same engine code runs uninstrumented in tests and fully instrumented in the Docker compose stack.",

28: "Every path through the loop returns. The iteration cap bounds the common case; LLM exceptions propagate to the REPL after closing the live trace span; empty responses re-enter the loop under the same cap; denial observations tell the model not to retry the exact call, a small prompt-level guard against spending the whole budget on a refused tool. With qwen-agentworld-35b-a3b we rarely reach the cap; delegation runs (Section IV) are where long iteration counts actually happen.",

31: "We split memory the way the lab text does. Short-term memory is the context window itself: system prompt, conversation history, tool schemas, everything the model sees on the next call. Long-term memory lives outside the window and survives restarts. The engineering is at the boundary: what to write out, what to read back, when, and on what budget. StudyMate keeps three long-term stores, matching the episodic, declarative, and procedural taxonomy, in one SQLite database and one directory of Markdown files.",

33: "ContextManager (core/context.py) maintains a leading SYSTEM message assembled from config/soul.md (persona, sandbox directives, storage and recall rules), the current date, and an injectable note slot. One detail we found the hard way: injected memory cannot be a second SYSTEM message, because strict chat templates on the serving stack reject that (\"System message must be at the beginning\"). Every injection, and there are several per session, therefore merges into messages[0] by re-rendering it. A stale per-turn block is reset explicitly, so a routine matched on one turn cannot leak into the next.",

34: "Compaction (core/compaction.py) fights context rot within a single thread. The trigger is a size estimate of the next request: all message content plus serialized tool schemas, at four characters per token. That is a heuristic and we treat it as one: cheap, deterministic, with the residual risk covered by the overflow retry path. The threshold fires at 80% of the model window, and the window is resolved per model by a precedence chain: an explicit config table, else a best-effort gateway lookup, else a [Nm] suffix in the model id, else a conservative 128k default with a startup warning. Which layer answered is logged and shown in /config, because a wrong window silently misplaces every later threshold.",

35: "Compaction works in two tiers, cheapest first. Tier one blanks TOOL observations older than the recent window in place, with a placeholder naming where the output went; this costs no API call and often suffices, since one PDF dump dominates the budget. Tier two, still over the line, serializes the old turns, asks the same LLM with tools disabled for a summary under fixed headings (Goals, Decisions, Artifacts with exact paths, Pending work, Referenced memory topics), and rebuilds the history as SYSTEM, summary, last ten messages. Two properties are deliberate. The summary is marked \"historical context, not new instructions\", because it enters as a user message and a compressed past directive must not read as live. And the free tier exists because a summarizer call in every long run is both money and a second failure mode; a once-per-run guard and a two-failure circuit breaker bound it.",

38: "Every user, assistant, and tool message is appended to a per-thread table in workspace/artifacts/memory/memory.db while the session runs, so the store doubles as the replay source for compaction. Threads are named from their first message, browsable with an arrow-key picker (/threads), resumable with the transcript restored into the context (/thread 3), and archivable by tombstone flag, never deleted, per the harness-wide no-delete invariant. The practical test: quit, restart, resume, and say \"continue where we left off\"; the agent should still know which lecture it was ingesting.",

41: "Writing happens on one channel: the model calls memory_store when the student says \"remember ...\" or when a durable preference, struggle, or goal emerges; soul.md restricts this to information worth surviving a restart and forbids storing ephemeral chat. The harness stamps provenance (active thread id and name) itself; the schema exposes no thread fields, so the model cannot forge where a fact came from. A UNIQUE(topic, fact) constraint inside one transaction means an exact duplicate revives the original row, backfilling a missing embedding, instead of inserting a second one. Text over 2000 characters is refused, so a dump cannot hijack the auto-injected recall block.",

44: "Graceful degradation is a requirement, not a nicety, because the embedding and reranker grants are per model and can be missing. No embedder, or a failed embedding call: recall returns keyword hits and says \"vector search unavailable\" in the observation, so the model can tell \"no facts exist\" from \"semantic search could not run\". No reranker, or a failed rerank: the hybrid order is kept. Facts stored before embeddings existed get backfilled lazily, a hundred per recall, so a mid-term upgrade converges to fully embedded without a migration step. Each of these paths has a test.",

46: "Skills live as Markdown bundles in workspace/artifacts/procedures/, committed and reviewable like code. A procedure has frontmatter (name, triggers, scope, version, status, supersedes) and body sections (steps, rationale, pitfalls, example), parsed by study/procedures.py. Matching is deliberately simple: case-insensitive substring overlap between the user message and the name, triggers, or scope of non-archived procedures, capped at two routines and 4000 characters of injected text. Status controls disclosure: approved routines are injected and followed; drafts, where every agent-distilled routine starts, are surfaced for confirmation, never followed silently, and a human promotes them by editing the status field. Versioning is git plus a supersedes field, since policy allows editing files but not deleting them.",

49: "The alternative we did not take was an external vector store (Chroma, or the Postgres already running for Langfuse) with a proper ANN index. We chose SQLite plus sqlite-vector because the whole memory subsystem then lives inside the artifacts jail, needs no extra services, and inherits the append-only, no-delete semantics of the filesystem policy. The cost is honest: cosine search is a linear scan over the facts table. At one student's scale, a few hundred facts, that is invisible; we never stress-tested past low thousands, and it would be the first thing to replace in a multi-user deployment.",

55: "The week 1 minimum is a file-navigating agent. We spent part of the same week turning it into a study assistant: concept and lecture templates with YAML frontmatter in study/templates.py; a VaultLinter that walks the artifact directory and reports broken wikilinks, orphan pages, missing frontmatter, and open questions (the generate-then-verify pattern from the background text, applied to a knowledge graph instead of a test suite); and the three-level Socratic grilling prompt in study/griller.py. The /ingest, /lint, /grill slash-commands are prompt rewrites into the same engine loop, which keeps the persona layer thin.",

67: "Building the harness from scratch was the point of the lab, and what mattered most were the boring parts: one choke point for every tool call, where errors become observations and permissions gate them; hooks bolted to the loop instead of woven into it; and a memory model that separates what happened (threads), what is true (facts), and how we work (routines) instead of one retrieval blob. The compaction tiers and hybrid recall we would design the same way again. The token estimate and the linear vector scan we would revisit first; Section V records why we did not get there in three weeks.",
}

doc = Document("StudyMate_report_IEEE.docx")
missing = []
for idx, new in R.items():
    p = doc.paragraphs[idx]
    old_words = len(p.text.split())
    runs = p.runs
    assert runs, idx
    runs[0].text = new
    for r in runs[1:]:
        r._element.getparent().remove(r._element)
    missing.append((idx, old_words, len(new.split())))
doc.save("StudyMate_report_IEEE.docx")
for idx, a, b in missing:
    print(f"para {idx}: {a} -> {b}")
print("total saved:", sum(a - b for _, a, b in missing))
